M48
; DRILL file {KiCad 8.99.0-unknown-8ec1016ccf~178~ubuntu22.04.1} date 2024-05-09T20:44:09+0530
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-09T20:44:09+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.99.0-unknown-8ec1016ccf~178~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1417
%
G90
G05
T1
X5.9417Y-3.9524
T2
X6.1709Y-3.1996
M30
