M48
; DRILL file {KiCad 8.99.0-unknown-2b81d3a93c~180~ubuntu22.04.1} date 2024-08-01T07:46:56+0530
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-01T07:46:56+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.99.0-unknown-2b81d3a93c~180~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1417
%
G90
G05
T1
X6.1709Y-3.1996
M30
